### ISSUE TITLE
多选状态，checkStrictly为false时——搜索时，如果返回的类目是到2级，点击能选上这个类目，但是却没有勾选此二级类目下的所有三级类目（如果有），并且级联面板中也没有显示。

### ISSUE THREAD

**Issue by linying-b** [zhuss/lazy-cascader#5]
![image](https://user-images.githubusercontent.com/56575056/99487099-8bafea00-29a0-11eb-97a2-61c3c8ae089d.png)
![image](https://user-images.githubusercontent.com/56575056/99487136-9cf8f680-29a0-11eb-8f50-f2d95181dcc7.png)

**Comment by zhuss** [comment]
搜索逻辑不应该出现中间节点
